_target_: src.models.multihead_lit_module.MultiheadLitModule

net:
  _target_: src.models.components.simple_efficientnet.SimpleEfficientNet
  input_channels: 3 # CIFAR-100-MH has 3 color channels
  heads_config:
    fine_label: 100 # Default - will be overridden by dataset
    coarse_label: 20 # Default - will be overridden by dataset
    texture: 8 # Default - will be overridden by dataset
  dropout_rate: 0.3

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.01

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: 100
  eta_min: 1e-5

# Different criterion per head (will be auto-configured based on dataset)
criteria:
  fine_label:
    _target_: torch.nn.CrossEntropyLoss
  coarse_label:
    _target_: torch.nn.CrossEntropyLoss
  texture:
    _target_: torch.nn.CrossEntropyLoss

# Loss weighting auto-configured from dataset JNDs (Just Noticeable Differences)
# JND-based weights: fine_label=100, coarse_label=20, texture=8 (based on number of classes)
# loss_weights: # Commented out - auto-configured from dataset metadata
