_target_: src.models.mnist_module.MNISTLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

criterion:
  _target_: torch.nn.CrossEntropyLoss

net:
  _target_: src.models.components.simple_dense_net.SimpleDenseNet
  input_size: 3072  # CIFAR-100 has 32x32x3 = 3072 features when flattened
  lin1_size: 200
  lin2_size: 400
  lin3_size: 620
  output_size: 100  # CIFAR-100 has 100 fine-grained classes

# compile model for faster training with pytorch 2.0
compile: false
