_target_: src.models.mnist_module.MNISTLitModule

net:
  _target_: src.models.components.convnext_v2.convnext_v2_cifar100_10m
  input_size: 32
  in_chans: 3
  output_size: 100

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.05 # Higher for larger model

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: 200 # Longer training
  eta_min: 1e-6

criterion:
  _target_: torch.nn.CrossEntropyLoss
  label_smoothing: 0.1 # Advanced training technique

compile: false
