_target_: src.models.mnist_module.MNISTLitModule

net:
  _target_: src.models.components.convnext_v2.convnext_v2_cifar10_128k
  input_size: 32 # CIFAR-10 is 32x32
  in_chans: 3 # CIFAR-10 has 3 color channels
  output_size: 10 # CIFAR-10 has 10 classes

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 0.0001 # Reduced from 0.01 to match CNN weight decay

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  _partial_: true
  T_max: 50 # Adjusted for CIFAR-10 training
  eta_min: 1e-5

criterion:
  _target_: torch.nn.CrossEntropyLoss

compile: false
