_target_: src.models.mnist_module.MNISTLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

criterion:
  _target_: torch.nn.CrossEntropyLoss

net:
  _target_: src.models.components.simple_efficientnet.SimpleEfficientNet
  input_channels: 3  # CIFAR-100 has 3 color channels
  num_classes: 100   # CIFAR-100 has 100 classes
  width_mult: 0.8    # Adjusted for CIFAR-100 complexity
  depth_mult: 1.0    # Standard depth
  dropout_rate: 0.3  # Higher dropout for more challenging dataset

# compile model for faster training with pytorch 2.0
compile: false
