_target_: src.models.multihead_lit_module.MultiheadLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

# Different criterion per head (will be auto-configured based on dataset)
# For CIFAR-100-MH, heads will be determined dynamically from the dataset
criteria:
  fine_label:
    _target_: torch.nn.CrossEntropyLoss
  coarse_label:
    _target_: torch.nn.CrossEntropyLoss
  texture:
    _target_: torch.nn.CrossEntropyLoss

# Loss weighting (equal weight to all heads by default)
loss_weights:
  fine_label: 1.0
  coarse_label: 1.0
  texture: 1.0

net:
  _target_: src.models.components.simple_cnn.SimpleCNN
  input_channels: 3 # CIFAR-100-MH has 3 color channels
  conv1_channels: 64
  conv2_channels: 128
  fc_hidden: 512
  heads_config:
    fine_label: 100 # Default - will be overridden by dataset
    coarse_label: 20 # Default - will be overridden by dataset
    texture: 8 # Default - will be overridden by dataset
  dropout: 0.5
  input_size: 32 # CIFAR-100-MH image size (32x32)

compile: false

# Auto-configure heads from dataset metadata
auto_configure_from_dataset: true
