_target_: src.models.mnist_module.MNISTLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

# Different criterion per head (or use same for all)
criteria:
  class:
    _target_: torch.nn.CrossEntropyLoss
  domain:
    _target_: torch.nn.CrossEntropyLoss
  mobility:
    _target_: torch.nn.CrossEntropyLoss
  size:
    _target_: torch.nn.CrossEntropyLoss

# Loss weighting (optional)
loss_weights:
  class: 1.0
  domain: 0.3
  mobility: 0.3
  size: 0.3

net:
  _target_: src.models.components.simple_cnn.SimpleCNN
  input_channels: 3  # CIFAR-10 has 3 color channels
  conv1_channels: 64
  conv2_channels: 128
  fc_hidden: 512
  heads_config:
    class: 10     # Original 10 classes
    domain: 2     # Living vs non-living
    mobility: 3   # Stationary/mobile/highly mobile
    size: 3       # Small/medium/large
  dropout: 0.5
  input_size: 32  # CIFAR-10 image size

compile: false
