_target_: src.models.mnist_module.MNISTLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

criterion:
  _target_: torch.nn.CrossEntropyLoss

net:
  _target_: src.models.components.simple_cnn.SimpleCNN
  input_channels: 3 # CIFAR-100 has 3 color channels
  input_size: 32 # CIFAR images are 32x32 pixels
  conv1_channels: 64
  conv2_channels: 128
  fc_hidden: 512
  output_size: 20 # CIFAR-100 has 20 coarse-grained superclasses
  dropout: 0.4 # Slightly lower dropout for easier 20-class task

# compile model for faster training with pytorch 2.0
compile: false
