# Cleaning targets

c clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage
	rm -rf ./viz/diagrams
	rm -rf ./outputs/

dc dclean: ## Clean data files
	rm -rf data-vimh/*

cl clean-logs: ## Clean logs
	rm -rf logs/**